# Generated by Django 4.2.7 on 2025-11-07 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, max_length=100)),
                ('account_type', models.CharField(choices=[('CHECKING', 'Расчетный счет'), ('SAVINGS', 'Сберегательный счет'), ('CREDIT', 'Кредитный счет'), ('DEPOSIT', 'Депозитный счет')], default='CHECKING', max_length=20)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('CLOSED', 'Закрыт'), ('BLOCKED', 'Заблокирован'), ('PENDING', 'Ожидает активации')], default='ACTIVE', max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('opened_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('type', models.CharField(choices=[('DEBIT', 'Списание'), ('CREDIT', 'Зачисление')], max_length=10)),
                ('status', models.CharField(choices=[('BOOKED', 'Проведена'), ('PENDING', 'Ожидает проведения'), ('CANCELLED', 'Отменена'), ('FAILED', 'Не удалась')], default='BOOKED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('merchant_account', models.CharField(blank=True, max_length=100)),
                ('booking_date', models.DateTimeField(db_index=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('transaction_code', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.CharField(default='CLOSING_BOOKED', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit_used', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounts.account')),
            ],
            options={
                'db_table': 'balances',
            },
        ),
        migrations.CreateModel(
            name='AccountSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('FULL', 'Полная'), ('DELTA', 'Дельта')], max_length=20)),
                ('transactions_synced', models.IntegerField(default=0)),
                ('new_transactions', models.IntegerField(default=0)),
                ('sync_start', models.DateTimeField()),
                ('sync_end', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'db_table': 'account_sync_logs',
            },
        ),
    ]
