# Generated by Django 4.2.7 on 2025-11-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.userbankprofile'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'booking_date'], name='transaction_account_84da59_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['booking_date'], name='transaction_booking_76b1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'status'], name='transaction_type_f4191c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['merchant_name'], name='transaction_merchan_69965e_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('account', 'transaction_id'), name='uniq_tx_per_account'),
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['account', 'last_updated'], name='balances_account_796320_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsynclog',
            index=models.Index(fields=['account', 'sync_start'], name='account_syn_account_7d5543_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsynclog',
            index=models.Index(fields=['sync_start'], name='account_syn_sync_st_487309_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user_profile', 'bank'], name='accounts_user_pr_1cacb2_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_id'], name='accounts_account_b1fcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['status', 'account_type'], name='accounts_status_c7c31e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['last_sync'], name='accounts_last_sy_f19df3_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user_profile', 'bank', 'account_id'), name='uniq_account_per_bank_per_user_profile'),
        ),
    ]
