import type {Metadata} from "next";
import '@mantine/core/styles/default-css-variables.css';
import '@mantine/core/styles/global.css';
import '@mantine/dates/styles.css';
import "./globals.css";
import localFont from "next/font/local";
import {Navbar} from "@/widgets/navbar";
import MantineClientProvider from "@/providers/MantineClientProvider";
import {ColorSchemeScript} from "@mantine/core";

const sfPro = localFont({
    src: [
        {
            path: "./fonts/SF-Pro-Display-Light.otf",
            weight: "300",
            style: "light",
        },
        {
            path: "./fonts/SF-Pro-Display-Regular.otf",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/SF-Pro-Display-Medium.otf",
            weight: "500",
            style: "medium",
        },
        {
            path: "./fonts/SF-Pro-Display-Semibold.otf",
            weight: "600",
            style: "semibold",
        },
        {
            path: "./fonts/SF-Pro-Display-Bold.otf",
            weight: "700",
            style: "bold",
        },
    ],
    variable: "--font-sf-pro",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Семейный Мультибанк",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
    return (
        <html lang="ru">
        <head>
            <ColorSchemeScript/>
        </head>
        <body
            className={`${sfPro.variable} antialiased bg-[#F8F9FB] text-white`}
        >
        <MantineClientProvider>
            <main className="py-4 w-full mx-auto max-w-screen-2xl relative">
                {children}
            </main>
            <Navbar/>
        </MantineClientProvider>
        </body>
        </html>
    );
}
