# Generated by Django 4.2.7 on 2025-11-07 17:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=100)),
                ('product_type', models.CharField(choices=[('DEPOSIT', 'Вклад'), ('LOAN', 'Кредит'), ('CARD', 'Карта'), ('ACCOUNT', 'Счет'), ('INVESTMENT', 'Инвестиционный продукт'), ('INSURANCE', 'Страхование')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('term_months', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('requirements', models.JSONField(default=dict)),
                ('documents_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('INACTIVE', 'Неактивный'), ('COMING_SOON', 'Скоро будет'), ('ARCHIVED', 'В архиве')], default='ACTIVE', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('promotion_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'Подана'), ('UNDER_REVIEW', 'На рассмотрении'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена'), ('CANCELLED', 'Отменена'), ('ADDITIONAL_INFO_REQUIRED', 'Требуется доп. информация')], default='DRAFT', max_length=30)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('requested_term', models.IntegerField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('application_data', models.JSONField(default=dict)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approved_term', models.IntegerField(blank=True, null=True)),
                ('approved_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.userbankprofile')),
            ],
            options={
                'db_table': 'product_applications',
                'indexes': [models.Index(fields=['user_profile', 'status'], name='product_app_user_pr_058b1f_idx'), models.Index(fields=['product', 'status'], name='product_app_product_2b00f4_idx'), models.Index(fields=['submitted_at'], name='product_app_submitt_57edfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAgreementConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('requesting_bank', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=50)),
                ('read_product_agreements', models.BooleanField(default=False)),
                ('open_product_agreements', models.BooleanField(default=False)),
                ('close_product_agreements', models.BooleanField(default=False)),
                ('allowed_product_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('EXPIRED', 'Истекло'), ('REVOKED', 'Отозвано')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.userbankprofile')),
            ],
            options={
                'db_table': 'product_agreement_consents',
                'indexes': [models.Index(fields=['user_profile', 'status'], name='product_agr_user_pr_76ec33_idx'), models.Index(fields=['requesting_bank', 'status'], name='product_agr_request_b8848b_idx'), models.Index(fields=['valid_until'], name='product_agr_valid_u_40f317_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('CLOSED', 'Закрыт'), ('PENDING', 'Ожидает активации'), ('SUSPENDED', 'Приостановлен'), ('EXPIRED', 'Истек')], default='ACTIVE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('term_months', models.IntegerField(blank=True, null=True)),
                ('opened_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_accrued', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.userbankprofile')),
            ],
            options={
                'db_table': 'product_agreements',
                'indexes': [models.Index(fields=['user_profile', 'status'], name='product_agr_user_pr_321879_idx'), models.Index(fields=['product', 'status'], name='product_agr_product_372565_idx'), models.Index(fields=['opened_date'], name='product_agr_opened__4bd811_idx'), models.Index(fields=['maturity_date'], name='product_agr_maturit_361ea7_idx'), models.Index(fields=['next_payment_date'], name='product_agr_next_pa_82127c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['bank', 'product_type'], name='products_bank_id_d38563_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'status'], name='products_product_b75a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'status'], name='products_is_feat_a3b38e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['promotion_end'], name='products_promoti_cf49d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('bank', 'product_id')},
        ),
    ]
