# Generated by Django 4.2.7 on 2025-11-07 17:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('invitation_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'auth_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('ACTIVE', 'Активно'), ('REJECTED', 'Отклонено'), ('EXPIRED', 'Истекло')], default='PENDING', max_length=20)),
                ('permissions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VBANK', 'Virtual Bank'), ('ABANK', 'Alpha Bank'), ('SBANK', 'Secure Bank'), ('CUSTOM', 'Custom Bank')], max_length=10)),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('base_url', models.URLField()),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_accounts', models.ManyToManyField(blank=True, through='banks.AccountSharing', to='banks.userbankprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100)),
                ('account_data', models.JSONField()),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.userbankprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(max_length=100, unique=True)),
                ('client_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AWAITING_AUTHORISATION', 'Ожидает авторизации'), ('AUTHORISED', 'Авторизовано'), ('REJECTED', 'Отклонено'), ('REVOKED', 'Отозвано'), ('EXPIRED', 'Истекло')], max_length=30)),
                ('permissions', models.JSONField(default=list)),
                ('expiration_date_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.userbankprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BankToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('token_type', models.CharField(default='bearer', max_length=50)),
                ('scope', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.userbankprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.UniqueConstraint(fields=('name', 'custom_name'), name='uniq_bank_name_custom'),
        ),
        migrations.AddField(
            model_name='accountsharing',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_in', to='banks.userbankprofile'),
        ),
        migrations.AddField(
            model_name='accountsharing',
            name='sharer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_out', to='banks.userbankprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.UniqueConstraint(fields=('user_profile', 'bank', 'account_id'), name='uniq_useraccount'),
        ),
        migrations.AddConstraint(
            model_name='banktoken',
            constraint=models.UniqueConstraint(fields=('user_profile', 'bank', 'token_type'), name='uniq_token_per_profile_bank_type'),
        ),
        migrations.AddConstraint(
            model_name='accountsharing',
            constraint=models.UniqueConstraint(fields=('sharer', 'receiver'), name='uniq_sharing_pair'),
        ),
    ]
