# Generated by Django 4.2.7 on 2025-11-07 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=100000, max_digits=15)),
                ('weekly_limit', models.DecimalField(decimal_places=2, default=500000, max_digits=15)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=2000000, max_digits=15)),
                ('per_transaction_limit', models.DecimalField(decimal_places=2, default=50000, max_digits=15)),
                ('daily_used', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('weekly_used', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_used', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_reset_daily', models.DateField(auto_now_add=True)),
                ('last_reset_weekly', models.DateField(auto_now_add=True)),
                ('last_reset_monthly', models.DateField(auto_now_add=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banks.userbankprofile')),
            ],
            options={
                'db_table': 'payment_limits',
            },
        ),
        migrations.CreateModel(
            name='PaymentConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('consent_type', models.CharField(choices=[('SINGLE_USE', 'Одноразовый'), ('MULTI_USE', 'Многоразовый'), ('VRP', 'Переменные регулярные платежи')], max_length=20)),
                ('status', models.CharField(choices=[('AWAITING_AUTHORISATION', 'Ожидает авторизации'), ('AUTHORISED', 'Авторизовано'), ('REJECTED', 'Отклонено'), ('REVOKED', 'Отозвано'), ('EXPIRED', 'Истекло')], max_length=30)),
                ('debtor_account', models.CharField(max_length=100)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('creditor_account', models.CharField(blank=True, max_length=100, null=True)),
                ('creditor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('max_amount_per_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allowed_creditor_accounts', models.JSONField(blank=True, default=list)),
                ('vrp_max_individual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vrp_daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vrp_monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.userbankprofile')),
            ],
            options={
                'db_table': 'payment_consents',
                'indexes': [models.Index(fields=['user_profile', 'consent_type'], name='payment_con_user_pr_45f856_idx'), models.Index(fields=['status', 'valid_until'], name='payment_con_status_8de8a9_idx'), models.Index(fields=['debtor_account'], name='payment_con_debtor__7f8f71_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=100)),
                ('consent_id', models.CharField(blank=True, max_length=100)),
                ('payment_type', models.CharField(choices=[('INTERNAL', 'Внутрибанковский'), ('EXTERNAL', 'Межбанковский'), ('TRANSFER', 'Перевод между своими счетами')], default='INTERNAL', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debtor_account', models.CharField(max_length=100)),
                ('creditor_account', models.CharField(max_length=100)),
                ('creditor_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает выполнения'), ('COMPLETED', 'Завершен'), ('FAILED', 'Неудачный'), ('CANCELLED', 'Отменен'), ('REJECTED', 'Отклонен банком')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
                ('creditor_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditor_payments', to='banks.bank')),
                ('debtor_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debtor_payments', to='banks.bank')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.userbankprofile')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile', 'created_at'], name='payments_user_pr_a1f7a9_idx'), models.Index(fields=['bank', 'payment_id'], name='payments_bank_id_8e6664_idx'), models.Index(fields=['status', 'created_at'], name='payments_status_426d4f_idx'), models.Index(fields=['debtor_account'], name='payments_debtor__5a351a_idx'), models.Index(fields=['creditor_account'], name='payments_credito_5ca5a3_idx')],
            },
        ),
    ]
